version: "3.8"

services:
  app:
    container_name: app.educaverso.course.service.api
    build: .
    profiles: [ "app" ]
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8000:8000"
    networks:
      - educaverso-network

networks:
  educaverso-network:
