version: "3.8"

services:
  app:
    hostname: educaverso-api
    container_name: app.educaverso.course.service.api
    build:
        context: ../../
        dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "${PORT}:${PORT}"
    networks:
      - educaverso-network
      - educaverso-services-network

networks:
  educaverso-network:
  educaverso-services-network:
    external: true
